apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"False","lastTransitionTime":"2020-12-27T09:58:17Z","reason":"FailedGetScale","message":"the
      HPA controller was unable to get the target''s current scale: deployments/scale.apps
      \"hello\" not found"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-12-26T21:21:18Z","reason":"FailedGetResourceMetric","message":"the
      HPA was unable to compute the replica count: unable to get metrics for resource
      cpu: no metrics returned from resource metrics API"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2020-12-26T14:49:04Z","reason":"TooFewReplicas","message":"the
      desired replica count is more than the maximum replica count"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"1m"}}]'
  creationTimestamp: "2020-12-26T08:43:57Z"
  name: hello
  namespace: default
  resourceVersion: "2019101"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/hello
  uid: 3a0054e0-03a6-4788-81d8-d02741917640
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 2
  desiredReplicas: 2
