apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hello-pdb-min
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hello
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hello-pdb-max
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: hello